name: Run autotests



on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Select tests to run\
        required: true
        type: choise
        default: all
        options:
          - all
          - smoke
          - regression


jobs:
  run-tests:
   runs-on: windows-10
   name: Tests
   steps: 
    - name: copy sourse code
      uses: actions/checkout@v4
    - name: Set up Python env
      uses: actions/setup-python@v5
      with: 
        python-version: "3.10"
    - name: install dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: pytest -v
    
